import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Using standard fonts temporarily to rule out CDN issues
const fonts = {
  regular: 'Helvetica',
  bold: 'Helvetica-Bold'
};

const styles = StyleSheet.create({
  page: {
    backgroundColor: '#0B1120',
    padding: 30,
    fontFamily: fonts.regular,
    color: '#E2E8F0',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#818CF8',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#94A3B8',
    marginBottom: 20,
  },
  summaryBlock: {
    padding: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 8,
    marginBottom: 20,
  },
  planName: {
    fontSize: 16,
    fontWeight: 600,
    color: '#818CF8',
    marginBottom: 5,
  },
  summaryText: {
    fontSize: 11,
    color: '#CBD5E1',
    lineHeight: 1.4,
  },
  disclaimer: {
    fontSize: 10,
    color: '#FBBF24',
    marginTop: 10,
    fontStyle: 'italic',
    padding: 8,
    backgroundColor: 'rgba(251, 191, 36, 0.05)',
    borderRadius: 4,
  },
  dayCard: {
    marginBottom: 15,
    padding: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 8,
  },
  dayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
    paddingBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  dayTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dayNumber: {
    marginRight: 10,
    padding: 5,
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    color: '#818CF8',
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 600,
  },
  dayName: {
    fontSize: 14,
    fontWeight: 600,
    color: '#F8FAFC',
  },
  dayType: {
    fontSize: 10,
    padding: '3 6',
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: '#CBD5E1',
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 600,
    color: '#94A3B8',
    textTransform: 'uppercase',
    marginBottom: 8,
    marginTop: 8,
  },
  warmupRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  warmupExercise: {
    fontSize: 11,
    color: '#E2E8F0',
    flex: 1,
  },
  warmupDuration: {
    fontSize: 11,
    color: '#94A3B8',
  },
  exerciseRow: {
    flexDirection: 'row',
    padding: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 6,
    marginBottom: 5,
    alignItems: 'center',
  },
  exerciseNumber: {
    width: 20,
    height: 20,
    backgroundColor: 'rgba(99, 102, 241, 0.2)',
    color: '#818CF8',
    fontSize: 10,
    fontWeight: 600,
    textAlign: 'center',
    paddingTop: 4,
    borderRadius: 4,
    marginRight: 10,
  },
  exerciseDetails: {
    flex: 1,
  },
  exerciseName: {
    fontSize: 12,
    fontWeight: 600,
    color: '#F8FAFC',
    marginBottom: 2,
  },
  exerciseDesc: {
    fontSize: 10,
    color: '#94A3B8',
  },
  overloadBox: {
    marginTop: 10,
    padding: 8,
    backgroundColor: 'rgba(99, 102, 241, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.2)',
    borderRadius: 6,
  },
  overloadText: {
    fontSize: 10,
    color: '#818CF8',
  },
  dailyTip: {
    fontSize: 10,
    color: '#94A3B8',
    fontStyle: 'italic',
    marginTop: 8,
    paddingLeft: 10,
    borderLeftWidth: 2,
    borderLeftColor: 'rgba(148, 163, 184, 0.3)',
  },
  muscleBadge: {
    fontSize: 8,
    fontWeight: 'bold',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    color: '#94A3B8',
    padding: '2 5',
    borderRadius: 3,
    marginRight: 4,
    marginTop: 4,
  },
  muscleContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  alternativesHeader: {
    fontSize: 8,
    fontWeight: 'bold',
    color: '#6366F1',
    marginTop: 6,
    textTransform: 'uppercase',
  },
  alternativeItem: {
    fontSize: 8,
    color: '#94A3B8',
    marginTop: 2,
    paddingLeft: 5,
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(99, 102, 241, 0.3)',
  }
});

interface WorkoutPdfProps {
  planData: any;
}

export const WorkoutPdfDocument: React.FC<WorkoutPdfProps> = ({ planData }) => {
  console.log("Rendering Workout PDF with data:", planData?.plan_name);
  if (!planData || !planData.days) return <Document><Page><Text>No data</Text></Page></Document>;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Workout Plan</Text>
        <Text style={styles.subtitle}>Generated by ArogyaMitra (AROMI)</Text>

        <View style={styles.summaryBlock}>
          <Text style={styles.planName}>{planData.plan_name}</Text>
          <Text style={styles.summaryText}>{planData.summary}</Text>
          {planData.disclaimer && (
            <Text style={styles.disclaimer}>{planData.disclaimer}</Text>
          )}
        </View>

        {planData.days.map((day: any, index: number) => (
          <View key={index} style={styles.dayCard} wrap={false}>
            <View style={styles.dayHeader}>
              <View style={styles.dayTitleContainer}>
                <Text style={styles.dayNumber}>D{day.day}</Text>
                <Text style={styles.dayName}>{day.day_name}</Text>
              </View>
              <Text style={styles.dayType}>{day.type}</Text>
            </View>

            {day.warmup?.length > 0 && (
              <View>
                <Text style={styles.sectionTitle}>Warmup</Text>
                {day.warmup.map((w: any, j: number) => (
                  <View key={j} style={styles.warmupRow}>
                    <Text style={styles.warmupExercise}>• {w.exercise}</Text>
                    <Text style={styles.warmupDuration}>{w.duration_mins} min</Text>
                  </View>
                ))}
              </View>
            )}

            {day.main_workout?.length > 0 && (
              <View>
                <Text style={styles.sectionTitle}>Exercises</Text>
                {day.main_workout.map((ex: any, j: number) => (
                  <View key={j} style={styles.exerciseRow}>
                    <Text style={styles.exerciseNumber}>{j + 1}</Text>
                    <View style={styles.exerciseDetails}>
                      <Text style={styles.exerciseName}>{ex.exercise}</Text>
                      <Text style={styles.exerciseDesc}>
                        {ex.sets} sets × {ex.reps} · {ex.rest_seconds}s rest
                      </Text>
                      
                      {ex.target_muscles && ex.target_muscles.length > 0 && (
                        <View style={styles.muscleContainer}>
                          {ex.target_muscles.map((m: string, k: number) => (
                            <Text key={k} style={styles.muscleBadge}>{m.toUpperCase()}</Text>
                          ))}
                        </View>
                      )}

                      {ex.alternatives && ex.alternatives.length > 0 && (
                        <View>
                          <Text style={styles.alternativesHeader}>Alternatives:</Text>
                          {ex.alternatives.map((alt: any, k: number) => (
                            <Text key={k} style={styles.alternativeItem}>• {alt.exercise}</Text>
                          ))}
                        </View>
                      )}
                    </View>
                  </View>
                ))}
              </View>
            )}

            {day.progressive_overload && (
              <View style={styles.overloadBox}>
                <Text style={styles.overloadText}>Progressive Overload: {day.progressive_overload}</Text>
              </View>
            )}

            {day.daily_tip && (
              <Text style={styles.dailyTip}>Daily Tip: {day.daily_tip}</Text>
            )}
          </View>
        ))}
      </Page>
    </Document>
  );
};
